### login
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "username": "newUser1",
  "password": "123456"
}
> {% client.global.set("auth_token", response.body.accessToken); %}




### test method
GET http://localhost:8080/test
Content-Type: application/json
Authorization: Bearer {{auth_token}}